#######################################################
############# Made By - Jonathan_Nathan ###############
#######################################################

# Commands
# Heal, Feed, FarmTime, GiveWand

Commands:
  Heal: true
  Feed: true
  Farmtime: true
  Givewand: true

# This is so you can set custom messages for the commands
#
# Default = "Sorry But this command has been disabled"
# prefix default = "&e&l[Jons-Stuff]"
# if you want to use color codes use &

# these will result in [Prefix] [disable Message] &cPermission: [Perms]
# EG: &e&l[Jons-Stuff] Sorry But this command has been disabled &cPermission: example.perm

Messages:
# this is the prefix for the plugin
  Prefix: "&e&l[Jons-Stuff]"
# The messages sent to a player if the command [heal] is disabled
  Heal-Disabled: "Sorry But this command has been disabled"
# The messages sent to a player if the command [feed] is disabled
  Feed-Disabled: "Sorry But this command has been disabled"
# The messages sent to a player if the command [farmtime] is disabled
  FarmTime-Disabled: "Sorry But this command has been disabled"
# The messages sent to a player if the command [givewand] is disabled
  GiveWand-Disabled: "Sorry But this command has been disabled"
# The messages sent to a player if the command [rld] is disabled
  Reload-Disabled: "Sorry But this command has been disabled"
# the message sent to the player if they dont have the permission
  NoPermission-Message: "&cMissing Permission"
# this is what on '&cPermission:' will be replaced with
  Permission-Tell: "&cPermission:"

# This is so you can change the default perms
# if the enabled = false it will use the default perm
# if the enabled = true it will use the custom perm specfied in the arguement

# default Enabled: false

Perms:
  Feed:
# the perm needed to execute the command feed
    enabled: false
    perm: "jonsstuff.command.feed"
  Heal:
# the perm needed to execute the command heal
    enabled: false
    perm: "jonsstuff.command.heal"
  FarmTime:
# the perm needed to execute the command farmtime
    enabled: false
    perm: "jonsstuff.command.farmtime"
  GiveWand:
# the perm needed to execute the command givewand
    enabled: false
    perm: "jonsstuff.command.givewand"
  Reload:
# the perm needed to execute the command reload
    enabled: false
    perm: "jonsstuff.reload"
 
