#######################################################
############# Made By - Jonathan_Nathan ###############
#######################################################

# Commands
# Heal, Feed, FarmTime, GiveWand

Commands:
  - Heal: true
  - Feed: true
  - FarmTime: true
  - GiveWand: true